### ISSUE TITLE
Deleting nested comment doesn't update the store to trigger re-render

### ISSUE THREAD

**Issue by bthompson1223** [bthompson1223/LaunchPad#66]
When deleting a nested comment, the store doesn't trigger a re-render in the component, however the comment is removed with a refresh and deleting a top level comment does trigger a re-render and deletes all children

**Comment by thechee** [comment]
Not sure how to tackle this. We will need to pass every level of parent into the action creator, or will need to do some logic to find the nested comment id in the state and delete it

**Comment by thechee** [comment]
https://www.npmjs.com/package/object-delete-key

We can consider using this package to take care of the logic for us

**Comment by bthompson1223** [comment]
Lei fixed nesting comments deleting bug
